apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: auction-api

  template:
    metadata:
      labels:
        app: auction-api

    spec:
      containers:
        - name: django
          image: kenhm25/auction-api:latest
          imagePullPolicy: Always
          
          command:
            - sh
            - -c
            - |
              python manage.py migrate &&
              gunicorn auctionsite.wsgi:application --bind 0.0.0.0:8000

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
                  
            - name: DB_HOST
              value: postgres
              
            - name: DEBUG
              value: "False"

            - name: ALLOWED_HOSTS
              value: "ken-auction.duckdns.org"

            - name: CSRF_TRUSTED_ORIGINS
              value: "https://ken-auction.duckdns.org"
          ports:
            - containerPort: 8000