apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auction-api

  template:
    metadata:
      labels:
        app: auction-api

    spec:
      containers:
        - name: django
          image: kenhm25/auction-api:latest
          imagePullPolicy: Always
          
          command:
            - sh
            - -c
            - |
              python manage.py migrate &&
              gunicorn auctionsite.wsgi:application --bind 0.0.0.0:8000

          env:
            - name: REDIS_HOST
              value: redis-service

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
                  
            - name: DB_HOST
              value: postgres
              
            - name: DEBUG
              value: "False"

            - name: ALLOWED_HOSTS
              value: "ken-auction.duckdns.org"

            - name: CSRF_TRUSTED_ORIGINS
              value: "https://ken-auction.duckdns.org"

            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: GOOGLE_OAUTH_CLIENT_ID
                  optional: true

            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: GOOGLE_OAUTH_CLIENT_SECRET
                  optional: true

            - name: GOOGLE_OAUTH_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: GOOGLE_OAUTH_REDIRECT_URI
                  optional: true

            - name: FRONTEND_OAUTH_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: FRONTEND_OAUTH_REDIRECT_URL
                  optional: true
          ports:
            - containerPort: 8000
          
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 5 
          
