apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auction-ingress

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auction-api
            port:
              number: 80