# Generated by Django 4.2.28 on 2026-02-27 13:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_highest_bid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
