# Generated by Django 4.2.28 on 2026-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_product_current_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_highest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
